---

- hosts: localhost
  connection: local
  become: true


  tasks:
  - name: Installing Htop to Desktop
    package:
      name: 
        - htop
        - tmux
        - vim-nox


  - name: Copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: nightking
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/background/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: nightkingd
    dconf: 
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
...

